---
title: "CEM Results"
author: "Skip Moses"
date: "4/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Joseph Shifman's exploring file
library(tidyverse)
library(ggplot2)
library(MatchIt)
library(lmtest)
library(sandwich)
```

## Summary

This is a document for Coarsened Exact Mathcing results.

## BIO104

```{r}
# 2017 Student grades/SI/demographic data
data <- read.csv("data/CEM_dataset.csv")
data.fall <- data %>% filter(Term.Type == "Fall")

# Remove Withdraws from class 
data.fall <- data.fall %>% 
  filter(Student.Class.Grade.Point.per.Unit > 0)

# COnvert to factors
data.fall$SI.Attended <- as.factor(data.fall$SI.Attended)
data.fall$Random.Student.ID <- as.factor(data.fall$Random.Student.ID)
data.fall$Random.Course.ID <- as.factor(data.fall$Random.Course.ID)

# Center the grade per unit
data.fall$Grade.Point.per.Unit.center <- (data.fall$Student.Class.Grade.Point.per.Unit - mean(data.fall$Student.Class.Grade.Point.per.Unit))/sd(data.fall$Student.Class.Grade.Point.per.Unit)
```


```{r}
# Estimate Propensity Scores
prop.score <- glm(SI.Attended ~ HS.GPA + 
                    Student.Orientation.Flag +
                    Major.1.STEM.Flag +
                    Random.Course.ID, family = binomial, data = data.fall)

summary(prop.score)

data.fall$Prop.Score <- predict(prop.score, type = "response")

labs <- paste("Actually Attended SI:", c("Did not Attend", "Attended"))

# Histogram of Propensity Scores
data.fall %>% mutate(SI.Attended = ifelse(SI.Attended == 1, labs[1], labs[2])) %>% 
  ggplot(aes(x = Prop.Score)) +
    geom_histogram(binwidth = .1) + facet_wrap(~SI.Attended) + xlab("Probability of goint to SI")
```


```{r}

# Here we make our matching. The k2K = TRUE will coarsen the covariates first
# and then do an exact matching on the coarsend data. This allows us to compute 
# the difference in grade between our matching.
matching <- matchit(SI.Attended ~ 
                      HS.GPA + 
                      Student.Orientation.Flag +
                      Major.1.STEM.Flag +
                      Random.Course.ID,
                    data = data.fall, method = 'cem', estimand = 'ATE',
                    k2k = TRUE,
                    k2k.method = "euclidean")

# Extract Matchings

matched_df1 <- match.data(matching) %>% arrange(subclass, SI.Attended)


# Split data into treatment and control
treatment <- matched_df1 %>% filter(SI.Attended == 1)
control <- matched_df1 %>% filter(SI.Attended == 0)

# Rejoin them so I can determine the grade difference 
matched_df2 <- full_join(treatment, control, by = "subclass")

# Treatment - Control ie Positive means SI student did better, Negative means Non SI student did.
matched_df2$Grade.diff <- matched_df2$Grade.Point.per.Unit.center.x - 
  matched_df2$Grade.Point.per.Unit.center.y

temp <- matched_df2 %>% select(subclass, Grade.diff)

matched_df1 <- matched_df1 %>% left_join(temp)

matched_df1$Grade.diff[matched_df1$SI.Attended == 0] <- -matched_df1$Grade.diff[matched_df1$SI.Attended ==1]

model1 <- glm(Grade.diff ~ Prop.Score  +
               IPEDS.Ethnicity.URM.Non.URM, data = matched_df1,
             weights = weights)

coeftest(model1, vcov. = vcovCL,
         cluster = ~subclass)
```

### Interpretation 

After controlling for other demographic, profile and HS GPA we see the propensity to go to SI is not significantly correlated with the difference in grade between matched pairs, but the difference is .2121 times less for under represented minorities (for a p value of 0.1)
