---
title: Exploring the Effect of Supplimental Instruction on Equity Gaps 
author:
  - name: Faith Fatchen
    affil: 1
  - name: Skip Moses
    affil: 1
  - name: Rica Rebusit
    affil: 1
  - name: Joseph Shifman
    affil: 1
  - name: Robin Donatello
    affil: 1
  - name: Eric Wasigner
    affil: 2
affiliation:
  - num: 1
    address: Department of Mathematics and Statistics, California State University, Chico
  - num: 2
    address: Department of Chemistry and Biochemistry, California State University, Chico
column_numbers: 4
primary_colour: "#9D2235"
secondary_colour: "#FFFFFF"
poster_height: "36in"
poster_width: "60in"
# logoright_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
# logoleft_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
output: 
  posterdown::posterdown_html:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

# Introduction

#### What is Supplemental Instruction?

  * Supplemental Instruction (SI) is a student lead homework session, where the SI leader is a student who has already received an A in the course. 
  * Students have diverse backgrounds, and some are not as prepared for college level material as others. SI aims bridge this gap, so every student has an equal opportunity at success. 

#### Related Work (Rica could put her summaries here)

  * 
  *

#### What is and Equity Gap?

# Methods

  <table>
<caption>Table 1: Population and Sample Comparison</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Variable </th>
   <th style="text-align:right;"> Chancelor.Data </th>
   <th style="text-align:right;"> Sample.Data </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Mean Number of Students </td>
   <td style="text-align:right;"> 16984 </td>
   <td style="text-align:right;"> 16075 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mean Percentage of Females </td>
   <td style="text-align:right;"> 54.27 </td>
   <td style="text-align:right;"> 53.34 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mean Percentage of Males </td>
   <td style="text-align:right;"> 45.72 </td>
   <td style="text-align:right;"> 46.61 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mean Percentage of First Gen. </td>
   <td style="text-align:right;"> 50.94 </td>
   <td style="text-align:right;"> 38.13 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Mean Percentage of URM </td>
   <td style="text-align:right;"> 36.66 </td>
   <td style="text-align:right;"> 37.55 </td>
  </tr>
</tbody>
</table>

#### Student Level

  *
  *
  *
  *
  *
  *
  *
  *

#### Course Level

  *
  *
  *
  *
  *
  *

# Student Level Models
  
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *

# Course Level Models 
  
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *
  *

# Future Work

  * Ideally, we want to identify attending SI as a treatment, and explore it's causal effect on equity gaps.
  * In order to accomplish this, we will employ Coarsened Exact Matching to control for counfounding variables. 
  * With this matching we can estimate the effect of SI on equity gaps with SI as a treatment as in a clinical trial. 
  
# Conclusions
