---
title: "Exploring the Effect of Supplemental Instruction on Equity Gaps"
author: "Faith Fatchen, Skip Moses, Rica Rebusit, Joseph Shifman"
date: "5/17/2022"
output: 
  beamer_presentation:
    theme: "AnnArbor"
    colortheme: "dolphin"
    fonttheme: "structurebold"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Original Source Data (via CSU Chico Instituional Research)
* Course Detail.csv
  - n = 43,803
  - Row contains record for course sections from Fall 2012 to Winter 2022
* Student Profile Metric.csv
  - n = 49,107
  - Row contains one record per student matriculation for students enrolled from Fall 2012 to Spring 2022
* Student Program.csv
  - n = 343,781
  - Row contains records for each semester of each student's attendance who were enrolled from Fall 2012 to Winter 2022
  
## Original Source Datasets (acquired via CSU Cico Instituional Research)
* SLC Appointment.csv
  - n = 78,229
  - Row contains record for each day that a student went to an SI session, and how many they went to in that day (Fall 2015 - Spring 2022)
* Student Grade.xlsx
  - n = 864,471
  - Row contains final grade data earned for each course for each student from Fall 2016 to Winter 2022
  
## Data Preparation
### Student Level Analysis


## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

