---
title: "Exploring the Effect of Supplemental Instruction on Equity Gaps"
author: "Faith Fatchen, Skip Moses, Rica Rebusit, Joseph Shifman"
date: "5/17/2022"
output: 
  beamer_presentation:
    theme: "AnnArbor"
    colortheme: "dolphin"
    fonttheme: "structurebold"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(Hmisc) # Enables %nin% notation for "not in"
library(readxl) # read Excel file
library(magrittr) #Allows %<>% notation to update lhs object with resulting value
library(naniar)
library(tinytex)
library(ggplot2)
library(stargazer)

course.level <- read_csv("data/course_analysis_dataset.csv")
course.level$Term.Year<-factor(course.level$Term.Year)
course.level$SI.Component.Flag<-factor(course.level$SI.Component.Flag)
No.SI <- filter(course.level, SI.Component.Flag == "0")
```


## Course Level Details

- Variables: avg HS GPA, First Gen, URM, class size, DWF rate, class average, SI component, term year
- Courses from term years 2016-2019
- URM and First Generation percentages
- Lower Division courses
- Courses with class size 20+

## URM and DWF Rate

```{r cars, echo = TRUE}
ggplot(course.level, aes(URM, dwf.rate, color = URM)) + geom_point() + facet_wrap(. ~Term.Year) + xlab("Percent URM") + ylab("DWF Rate") + geom_point(data=No.SI, aes(x=URM, y=dwf.rate), color = 'red') + theme(legend.position="none") + geom_smooth(se=F) 
```

## First Generation and DWF Rate

```{r pressure}
ggplot(course.level, aes(First.Gen.Perc, dwf.rate, color = First.Gen.Perc)) + geom_point() + facet_wrap(. ~Term.Year) + xlab("Percent First Gen") + ylab("DWF Rate")+ geom_point(data=No.SI, aes(x=URM, y=dwf.rate), color = 'red') + theme(legend.position="none") + geom_smooth(se=F)
```

## Course Level Modelling

```{r, results = 'asis', echo = FALSE}
stargazer(m, m2, off.ratio=T, single.row = TRUE, type = "latex", title = "Results Multilinear Regression")
```

